# Generated by Django 5.0.7 on 2025-06-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_blog_slug_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog'),
        ),
        migrations.AlterField(
            model_name='savedblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog'),
        ),
    ]
