# Generated by Django 5.0.7 on 2025-06-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_alter_comment_blog_alter_savedblog_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
